// Generated by scripts/embed-migrations.ts — do not edit.
// Source: packages/db/src/migrations/*.sql (drizzle-kit generate)

export interface EmbeddedMigration {
  tag: string;
  hash: string;
  statements: string[];
}

export const migrations: EmbeddedMigration[] = [
  {
    "tag": "0000_plain_komodo",
    "hash": "bdfa8ab91b36f02a1e4cecc94930f971cf6fd9682f0dcfe874adb2d1c25a6704",
    "statements": [
      "CREATE TABLE \"projects\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"name\" text NOT NULL,\r\n\t\"owner_id\" text DEFAULT '' NOT NULL,\r\n\t\"created_at\" bigint NOT NULL,\r\n\t\"updated_at\" bigint NOT NULL,\r\n\t\"thumbnail\" text,\r\n\t\"artboards\" integer,\r\n\t\"animations\" integer,\r\n\t\"state_machines\" integer,\r\n\t\"shared_with\" jsonb,\r\n\t\"doc\" text,\r\n\t\"riv\" \"bytea\"\r\n);",
      "CREATE TABLE \"settings\" (\r\n\t\"key\" text PRIMARY KEY NOT NULL,\r\n\t\"value\" jsonb NOT NULL\r\n);",
      "CREATE TABLE \"users\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"name\" text NOT NULL,\r\n\t\"color\" text NOT NULL,\r\n\t\"role\" text DEFAULT 'editor' NOT NULL,\r\n\t\"created_at\" bigint NOT NULL,\r\n\t\"position\" integer DEFAULT 0 NOT NULL\r\n);"
    ]
  },
  {
    "tag": "0001_odd_felicia_hardy",
    "hash": "acca953638c4ba067f5437d3a31cb563aeb9fc2088a81886d034b85881ff616d",
    "statements": [
      "CREATE TABLE \"sessions\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"user_id\" text NOT NULL,\r\n\t\"created_at\" bigint NOT NULL,\r\n\t\"expires_at\" bigint NOT NULL,\r\n\t\"agent\" text\r\n);",
      "ALTER TABLE \"users\" ADD COLUMN \"email\" text;",
      "ALTER TABLE \"users\" ADD COLUMN \"password_hash\" text;",
      "ALTER TABLE \"users\" ADD COLUMN \"disabled\" boolean DEFAULT false NOT NULL;",
      "ALTER TABLE \"users\" ADD COLUMN \"last_login_at\" bigint;",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;"
    ]
  },
  {
    "tag": "0002_better_auth",
    "hash": "964943a099070d5690215ff77da56a7fd057c47958ba5c7aba023e13c28f332e",
    "statements": [
      "ALTER TABLE \"users\" ADD COLUMN \"email_verified\" boolean DEFAULT false NOT NULL;",
      "ALTER TABLE \"users\" ADD COLUMN \"image\" text;",
      "ALTER TABLE \"users\" ALTER COLUMN \"created_at\" SET DATA TYPE timestamp with time zone USING to_timestamp(\"created_at\" / 1000.0);",
      "ALTER TABLE \"users\" ALTER COLUMN \"created_at\" SET DEFAULT now();",
      "ALTER TABLE \"users\" ALTER COLUMN \"last_login_at\" SET DATA TYPE timestamp with time zone USING to_timestamp(\"last_login_at\" / 1000.0);",
      "ALTER TABLE \"users\" ADD COLUMN \"updated_at\" timestamp with time zone DEFAULT now() NOT NULL;",
      "ALTER TABLE \"users\" ADD CONSTRAINT \"users_email_unique\" UNIQUE(\"email\");",
      "CREATE TABLE \"accounts\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"user_id\" text NOT NULL,\r\n\t\"account_id\" text NOT NULL,\r\n\t\"provider_id\" text NOT NULL,\r\n\t\"password\" text,\r\n\t\"access_token\" text,\r\n\t\"refresh_token\" text,\r\n\t\"id_token\" text,\r\n\t\"access_token_expires_at\" timestamp with time zone,\r\n\t\"refresh_token_expires_at\" timestamp with time zone,\r\n\t\"scope\" text,\r\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\r\n);",
      "ALTER TABLE \"accounts\" ADD CONSTRAINT \"accounts_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "INSERT INTO \"accounts\" (\"id\", \"user_id\", \"account_id\", \"provider_id\", \"password\", \"created_at\", \"updated_at\")\r\n\tSELECT md5(random()::text || \"id\"), \"id\", \"id\", 'credential', \"password_hash\", now(), now()\r\n\tFROM \"users\" WHERE \"password_hash\" IS NOT NULL;",
      "ALTER TABLE \"users\" DROP COLUMN \"password_hash\";",
      "CREATE TABLE \"verifications\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"identifier\" text NOT NULL,\r\n\t\"value\" text NOT NULL,\r\n\t\"expires_at\" timestamp with time zone NOT NULL,\r\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\r\n);",
      "DROP TABLE \"sessions\";",
      "CREATE TABLE \"sessions\" (\r\n\t\"id\" text PRIMARY KEY NOT NULL,\r\n\t\"user_id\" text NOT NULL,\r\n\t\"token\" text NOT NULL,\r\n\t\"expires_at\" timestamp with time zone NOT NULL,\r\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t\"ip_address\" text,\r\n\t\"user_agent\" text,\r\n\tCONSTRAINT \"sessions_token_unique\" UNIQUE(\"token\")\r\n);",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;"
    ]
  },
  {
    "tag": "0003_cute_starbolt",
    "hash": "9c9fbbd2e132eb435feff5c06b4ddd54da6c1f5a0d9fb618c37f7406f7f0a58d",
    "statements": [
      "CREATE TABLE \"rate_limit\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"count\" integer NOT NULL,\n\t\"last_request\" bigint NOT NULL,\n\tCONSTRAINT \"rate_limit_key_unique\" UNIQUE(\"key\")\n);"
    ]
  }
];
