// Generated by scripts/embed-migrations.ts — do not edit.
// Source: packages/db/src/migrations/*.sql (drizzle-kit generate)

export interface EmbeddedMigration {
  tag: string;
  hash: string;
  statements: string[];
}

export const migrations: EmbeddedMigration[] = [
  {
    "tag": "0000_plain_komodo",
    "hash": "ee8950309fa646fd7979734d982f22abe6e6cac2c7a107fde337a68d27176615",
    "statements": [
      "CREATE TABLE \"projects\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"owner_id\" text DEFAULT '' NOT NULL,\n\t\"created_at\" bigint NOT NULL,\n\t\"updated_at\" bigint NOT NULL,\n\t\"thumbnail\" text,\n\t\"artboards\" integer,\n\t\"animations\" integer,\n\t\"state_machines\" integer,\n\t\"shared_with\" jsonb,\n\t\"doc\" text,\n\t\"riv\" \"bytea\"\n);",
      "CREATE TABLE \"settings\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"value\" jsonb NOT NULL\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"color\" text NOT NULL,\n\t\"role\" text DEFAULT 'editor' NOT NULL,\n\t\"created_at\" bigint NOT NULL,\n\t\"position\" integer DEFAULT 0 NOT NULL\n);"
    ]
  },
  {
    "tag": "0001_odd_felicia_hardy",
    "hash": "3356403e30b357aedcc2f46643b19207a97ef4f203650351efe32e1b9b099907",
    "statements": [
      "CREATE TABLE \"sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"created_at\" bigint NOT NULL,\n\t\"expires_at\" bigint NOT NULL,\n\t\"agent\" text\n);",
      "ALTER TABLE \"users\" ADD COLUMN \"email\" text;",
      "ALTER TABLE \"users\" ADD COLUMN \"password_hash\" text;",
      "ALTER TABLE \"users\" ADD COLUMN \"disabled\" boolean DEFAULT false NOT NULL;",
      "ALTER TABLE \"users\" ADD COLUMN \"last_login_at\" bigint;",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;"
    ]
  },
  {
    "tag": "0002_better_auth",
    "hash": "86e24eabe226d1ad3198929259bf6486485513fc5549d1ace6e6fbfbadc7aded",
    "statements": [
      "ALTER TABLE \"users\" ADD COLUMN \"email_verified\" boolean DEFAULT false NOT NULL;",
      "ALTER TABLE \"users\" ADD COLUMN \"image\" text;",
      "ALTER TABLE \"users\" ALTER COLUMN \"created_at\" SET DATA TYPE timestamp with time zone USING to_timestamp(\"created_at\" / 1000.0);",
      "ALTER TABLE \"users\" ALTER COLUMN \"created_at\" SET DEFAULT now();",
      "ALTER TABLE \"users\" ALTER COLUMN \"last_login_at\" SET DATA TYPE timestamp with time zone USING to_timestamp(\"last_login_at\" / 1000.0);",
      "ALTER TABLE \"users\" ADD COLUMN \"updated_at\" timestamp with time zone DEFAULT now() NOT NULL;",
      "ALTER TABLE \"users\" ADD CONSTRAINT \"users_email_unique\" UNIQUE(\"email\");",
      "CREATE TABLE \"accounts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"provider_id\" text NOT NULL,\n\t\"password\" text,\n\t\"access_token\" text,\n\t\"refresh_token\" text,\n\t\"id_token\" text,\n\t\"access_token_expires_at\" timestamp with time zone,\n\t\"refresh_token_expires_at\" timestamp with time zone,\n\t\"scope\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"accounts\" ADD CONSTRAINT \"accounts_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "INSERT INTO \"accounts\" (\"id\", \"user_id\", \"account_id\", \"provider_id\", \"password\", \"created_at\", \"updated_at\")\n\tSELECT md5(random()::text || \"id\"), \"id\", \"id\", 'credential', \"password_hash\", now(), now()\n\tFROM \"users\" WHERE \"password_hash\" IS NOT NULL;",
      "ALTER TABLE \"users\" DROP COLUMN \"password_hash\";",
      "CREATE TABLE \"verifications\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"identifier\" text NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "DROP TABLE \"sessions\";",
      "CREATE TABLE \"sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"token\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"ip_address\" text,\n\t\"user_agent\" text,\n\tCONSTRAINT \"sessions_token_unique\" UNIQUE(\"token\")\n);",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;"
    ]
  },
  {
    "tag": "0003_cute_starbolt",
    "hash": "9c9fbbd2e132eb435feff5c06b4ddd54da6c1f5a0d9fb618c37f7406f7f0a58d",
    "statements": [
      "CREATE TABLE \"rate_limit\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"count\" integer NOT NULL,\n\t\"last_request\" bigint NOT NULL,\n\tCONSTRAINT \"rate_limit_key_unique\" UNIQUE(\"key\")\n);"
    ]
  },
  {
    "tag": "0004_rare_jetstream",
    "hash": "4736072bd358a8551520c058a5a33d5181f8bbc5c9c829c9e49cb6164205ce74",
    "statements": [
      "ALTER TABLE \"projects\" ADD COLUMN \"riv_storage_key\" text;"
    ]
  },
  {
    "tag": "0005_low_queen_noir",
    "hash": "57e800c9925185eaf3fe8d0245186ddc9fa6b901995e483837ff1811b56cd4f6",
    "statements": [
      "CREATE TABLE \"apikey\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"config_id\" text DEFAULT 'mcp' NOT NULL,\n\t\"name\" text,\n\t\"start\" text,\n\t\"reference_id\" text NOT NULL,\n\t\"prefix\" text,\n\t\"key\" text NOT NULL,\n\t\"refill_interval\" integer,\n\t\"refill_amount\" integer,\n\t\"last_refill_at\" timestamp with time zone,\n\t\"enabled\" boolean DEFAULT true NOT NULL,\n\t\"rate_limit_enabled\" boolean DEFAULT true NOT NULL,\n\t\"rate_limit_time_window\" integer DEFAULT 86400000 NOT NULL,\n\t\"rate_limit_max\" integer DEFAULT 10 NOT NULL,\n\t\"request_count\" integer DEFAULT 0 NOT NULL,\n\t\"remaining\" integer,\n\t\"last_request\" timestamp with time zone,\n\t\"expires_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"permissions\" text,\n\t\"metadata\" text\n);",
      "CREATE INDEX \"apikey_reference_id_idx\" ON \"apikey\" USING btree (\"reference_id\");",
      "CREATE INDEX \"apikey_key_idx\" ON \"apikey\" USING btree (\"key\");"
    ]
  }
];
