// Turns packages/db/src/migrations/*.sql into a TypeScript module.
//
// Drizzle's own migrator reads the folder at run time, which does not survive
// bundling (Next.js standalone output, the desktop app bundle or a Docker image
// built from sources). Embedding the statements keeps one schema history that
// works everywhere. Run it after `drizzle-kit generate` (bun run db:generate).
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dir, '..');
const dir = path.join(root, 'packages', 'db', 'src', 'migrations');
const journal = JSON.parse(readFileSync(path.join(dir, 'meta', '_journal.json'), 'utf8')) as {
  entries: { idx: number; tag: string; when: number }[];
};

const migrations = journal.entries
  .sort((a, b) => a.idx - b.idx)
  .map((entry) => {
    const sql = readFileSync(path.join(dir, `${entry.tag}.sql`), 'utf8');
    return {
      tag: entry.tag,
      // same hash as drizzle-kit's migrator, so both ways of applying agree
      hash: createHash('sha256').update(sql).digest('hex'),
      statements: sql
        .split('--> statement-breakpoint')
        .map((s) => s.trim())
        .filter(Boolean),
    };
  });

const file = `// Generated by scripts/embed-migrations.ts — do not edit.
// Source: packages/db/src/migrations/*.sql (drizzle-kit generate)

export interface EmbeddedMigration {
  tag: string;
  hash: string;
  statements: string[];
}

export const migrations: EmbeddedMigration[] = ${JSON.stringify(migrations, null, 2)};
`;

await Bun.write(path.join(root, 'packages', 'db', 'src', 'migrations.generated.ts'), file);
console.log(`Embedded ${migrations.length} migration(s): ${migrations.map((m) => m.tag).join(', ')}`);
